##############################
# inStrain profile queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/Abigail/executables/inStrain-queues.sh

request_cpus = 6
request_memory = 150GB
arguments = $(genome) $(mapping)

output = /home/GLBRCORG/emcdaniel/EBPR/Abigail/outs/$(Cluster)_$(Process)_quick_profile.out
error = /home/GLBRCORG/emcdaniel/EBPR/Abigail/errs/$(Cluster)_$(Process)_quick_profile.err
log = /home/GLBRCORG/emcdaniel/EBPR/Abigail/logs/$(Cluster)_$(Process)_quick_profile.log

queue genome,mapping from metadata/Abigail-inStrain-queues.txt