##################
# mapMetasToAssembs.sub
# Submission script for mapping metagenomic reads to assemblies
# Elizabeth McDaniel
##################

request_cpus = 6
request_memory = 50GB

executable = /home/GLBRCORG/emcdaniel/EBPR/Abigail/executables/mapping_metas_to_assemblies.sh
arguments = $(ref) $(meta) $(out)

output = /home/GLBRCORG/emcdaniel/EBPR/Abigail/outs/$(Cluster)_$(Process)_mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/Abigail/errs/$(Cluster)_$(Process)_mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/Abigail/logs/$(Cluster)_$(Process)_mapping.log

queue ref,meta,out from metadata/Abigail-mapping-queues.txt
